displayName=GMC Flip Tracker
author=Zentosplay
description=Envia suas transacoes da Grand Exchange ao GetMasterCrafter para o seu Profit Tracker.
tags=grand exchange,flipping,tracker,getmastercrafter,profit
version=
plugins=com.getmastercrafter.fliptracker.GmcFlipTrackerPlugin
build=standard