displayName=GMC Flip Tracker
author=Zentosplay
description=Sends your Grand Exchange trades to GetMasterCrafter for your Profit Tracker.
tags=grand exchange,flipping,tracker,getmastercrafter,profit
version=
plugins=com.getmastercrafter.fliptracker.GmcFlipTrackerPlugin
build=standard